services:
  foxglove_bridge:
    build:
      context: .
      dockerfile: ./foxglove_bridge_docker/Dockerfile
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://${ROS_IP}:11311
      - ROS_IP=${ROS_IP}
    restart: unless-stopped